/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.ventas.sistema.gui;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import mx.com.ventas.sistema.datos.BaseDatos;
import mx.com.ventas.sistema.pojos.DetalleVenta;
import mx.com.ventas.sistema.pojos.Producto;
import mx.com.ventas.sistema.pojos.Ventas;

/**
 *
 * @author Ivan Rojo
 */
public class VentasFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    DefaultTableModel modeloTablaProductos = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    DefaultListModel<Producto> modeloListaProductos = new DefaultListModel<Producto>();
    BaseDatos db = new BaseDatos();
    
    public VentasFrame() {
        initComponents();
        cargarColumnasTablas();
        cargarListenerModeloTabla();
        
    }
    
    private void cargarListenerModeloTabla(){
        modeloTablaProductos.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {//SE CARGA CUANDO HAY UN CAMBIO EN LA TABLA
                int numFilas = modeloTablaProductos.getRowCount();
                //Variable PARA GUARDAR SUMATORIA
                double sumatoria = 0;
                for (int i=0; i<numFilas; i++){
                    String importe = (String) modeloTablaProductos.getValueAt(i, 4);
                    sumatoria += Double.parseDouble(importe);
                    
                }
                
                lblSumatoria.setText(String.valueOf(sumatoria));
            }
        });
    }
    
    private void cargarColumnasTablas(){
        
        modeloTablaProductos.addColumn("Clave");
        modeloTablaProductos.addColumn("Nombre");
        modeloTablaProductos.addColumn("Precio Venta");
        modeloTablaProductos.addColumn("Cantidad");
        modeloTablaProductos.addColumn("Importe");
    
    }
    private void anadirProductoAVenta(Producto producto){
        String claveProd = producto.getIdProducto();
        String nombreProd = producto.getNomProducto();
        String precioVenta = String.valueOf(producto.getPrecioVentaProducto());
        String importe = String.valueOf(producto.getPrecioVentaProducto());
        
        String [] datosProducto = {claveProd, nombreProd, precioVenta, "1", importe};
        modeloTablaProductos.addRow(datosProducto);
        
    }
    
    private void limpiarTabla() {
        int numFilas = modeloTablaProductos.getRowCount();
        if(numFilas >0){
            for(int i=numFilas-1;i>=0;i-- ){
                
                modeloTablaProductos.removeRow(i);
                
            }
        }
    }
    private void limpiarListaProd() {
        modeloListaProductos.clear();
    }
    private void desplegarFoto(Producto prod){
        ImageIcon imagenProducto =null;
        try{
            //obtener imagen
            InputStream is = db.buscarFoto(prod);
            BufferedImage bi = ImageIO.read(is);
            imagenProducto = new ImageIcon(bi);
            
            //Redimension de imagen para ajustarla al tamaño del JLabel
            Image imgProd = imagenProducto.getImage();
            int anchoEtiqueta = lblImagen.getWidth();
            int altoEtiqueta = lblImagen.getHeight();
            
            //Se crea un nuevo objeto Image con la imagen redimensionada
            Image imgRedimensionada = imgProd.getScaledInstance(anchoEtiqueta, altoEtiqueta, Image.SCALE_DEFAULT);
            
            //Crea un nuevo objeto ImagenIcon a partir de la imagen redimensionada
            ImageIcon iconRedimensionado = new ImageIcon(imgRedimensionada);
            
            //Establecemos la imagen reidmensionada como icono de la etiqueta de imagen
            lblImagen.setIcon(iconRedimensionado);
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(InventariosFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoBuscarProd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblSumatoria = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRealizarVenta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoPagaCon = new javax.swing.JTextField();
        btnQuitaProd = new javax.swing.JButton();
        btnCancelarVent = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaBuscarProd = new javax.swing.JList<>();
        btnCorteDia = new javax.swing.JButton();

        setTitle("Ventas");

        tablaProductos.setModel(modeloTablaProductos);
        tablaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaProductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jLabel1.setText("Buscar producto:");

        campoBuscarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBuscarProdKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSumatoria.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblSumatoria.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Venta Total:");

        btnRealizarVenta.setBackground(new java.awt.Color(153, 153, 255));
        btnRealizarVenta.setText("Realizar venta");
        btnRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVentaActionPerformed(evt);
            }
        });

        jLabel4.setText("Pago con: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRealizarVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblSumatoria))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoPagaCon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPagaCon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRealizarVenta)
                .addContainerGap())
        );

        btnQuitaProd.setText("Quitar producto");
        btnQuitaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitaProdActionPerformed(evt);
            }
        });

        btnCancelarVent.setText("Cancelar venta");
        btnCancelarVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        listaBuscarProd.setModel(modeloListaProductos);
        listaBuscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaBuscarProdMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listaBuscarProd);

        btnCorteDia.setText("Corte del dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnQuitaProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelarVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(campoBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCorteDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCorteDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitaProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarVent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitaProdActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaProductos.getSelectedRow();
        int cantidadFilas = modeloTablaProductos.getRowCount();
        if(cantidadFilas > 0){
            int opcion = JOptionPane.showConfirmDialog(this, "¿Deseas quitar este "
                + "producto de tu compra?");
                if(opcion==0){
                modeloTablaProductos.removeRow(filaSeleccionada);
                }
        }
        
    }//GEN-LAST:event_btnQuitaProdActionPerformed

    private void campoBuscarProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscarProdKeyReleased
        // TODO add your handling code here:
        limpiarListaProd();
        String cadenaBusqueda = campoBuscarProd.getText();
        if(cadenaBusqueda.isEmpty()){
            limpiarListaProd();
        }
        else{
        ArrayList<Producto> listaProductos = db.Buscaproducto(cadenaBusqueda);
        
        
        
        for(Producto prod: listaProductos){
            modeloListaProductos.addElement(prod);
            
        }
        }
    }//GEN-LAST:event_campoBuscarProdKeyReleased

    private void listaBuscarProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaBuscarProdMousePressed
        // TODO add your handling code here:
        JList list = (JList)evt.getSource();
        if(evt.getClickCount()==2){
            int index = list.locationToIndex(evt.getPoint());
            System.out.println("El index es: "+index);
            Producto prod = (Producto)list.getSelectedValue();
            System.out.println("El producto es: "+prod);
            anadirProductoAVenta(prod);
            
            desplegarFoto(prod);
            
        }
    }//GEN-LAST:event_listaBuscarProdMousePressed

    private void tablaProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProductosKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_F2){
            int filaSeleccionada = tablaProductos.getSelectedRow();
            String cantidad = JOptionPane.showInputDialog("Modificar cantidad: ");
            String precioVenta = (String) modeloTablaProductos.getValueAt(filaSeleccionada, 2);
            double importe = Double.parseDouble(cantidad)*Double.parseDouble(precioVenta);
            String importeString = String.valueOf(importe);
            modeloTablaProductos.setValueAt(cantidad, filaSeleccionada, 3);
            modeloTablaProductos.setValueAt(importeString, filaSeleccionada, 4);
        }
    }//GEN-LAST:event_tablaProductosKeyReleased

    private void btnCancelarVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentActionPerformed
        // TODO add your handling code here:
        int numFilas = modeloTablaProductos.getRowCount();
        int cantidadFilas = modeloTablaProductos.getRowCount();
        if(cantidadFilas > 0){
            int opcion = JOptionPane.showConfirmDialog(this, "¿Deseas cancelar tu venta?");
        if(opcion==0){
            for(int i=numFilas-1; i>=0; i--){
                modeloTablaProductos.removeRow(i);
            }
        }
        }
        
    }//GEN-LAST:event_btnCancelarVentActionPerformed

    private void btnRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVentaActionPerformed
        
        
        ArrayList<DetalleVenta> detalleventa = new ArrayList<DetalleVenta>();
        
        //Obtener la sumatoria de la venta
        String sumatoriaStr = lblSumatoria.getText();
        double montoVenta = Double.parseDouble(sumatoriaStr);
        
        String pagoConStr = campoPagaCon.getText();
        double cambio = 0;
        if(!pagoConStr.isEmpty()){
            double montoPago = Double.parseDouble(pagoConStr);
            cambio = montoPago-montoVenta;
        }
        
        
        //Obtener la fecha actual y creamos el objeto Date SQL
        Calendar calendarioLocal = Calendar.getInstance();
        java.util.Date fechaActual = calendarioLocal.getTime();
        long fechaMilisegundos = fechaActual.getTime();
        java.sql.Date fecha = new Date(fechaMilisegundos);
        
        Ventas venta = new Ventas(montoVenta, fecha);
        Long idVenta = db.insertarVenta(venta);
        
        int numFilas = modeloTablaProductos.getRowCount();
        for(int i =0; i<numFilas;i++){
            String idProducto = (String) modeloTablaProductos.getValueAt(i, 0);
            
            String cantidadStr = (String) modeloTablaProductos.getValueAt(i, 3);
            
            double cantidad = Double.parseDouble(cantidadStr);
            
            DetalleVenta detalle = new DetalleVenta(idVenta, idProducto, cantidad);
            db.insertarDetalleVenta(detalle);
            detalleventa.add(detalle);
        }
        
        for(int i=numFilas-1; i>=0; i--){
                modeloTablaProductos.removeRow(i);
            }
    
        lblSumatoria.setText("0.0");
        if(!pagoConStr.isEmpty()){
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-size:200 px; color:blue'>"+cambio+"</h1></html>", "Usted debe dar este cambio",1);
            campoPagaCon.setText("");
        }
    }//GEN-LAST:event_btnRealizarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVent;
    private javax.swing.JButton btnCorteDia;
    private javax.swing.JButton btnQuitaProd;
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JTextField campoBuscarProd;
    private javax.swing.JTextField campoPagaCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSumatoria;
    private javax.swing.JList<Producto> listaBuscarProd;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables

    
}
