/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.gaby;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan Rojo
 */
public class Borrar extends javax.swing.JFrame {

    /**
     * Creates new form Borrar
     */
    DefaultTableModel model;
    public Borrar() {
        initComponents();
        cargar();
        limpiar();
        bloquear();
    }
    
    void bloquear(){
        clave.setEnabled(false);
        
        
    }
    
    void desbloquear(){
        clave.setEnabled(true);
        
    }
    void limpiar(){
        buscar.setText("");
    }
    

    void filtrar(String valor){
         String [] titulos={"clvasig","grupo","mat","profesor","lunes","martes","miercoles","jueves","viernes","salon","cupo"};
        String [] registro=new String[11];
        String sql="SELECT * FROM unsemestre where CONCAT(clvasig,' ',grupo,' ',mat,' ',profesor,' ',lunes,' ',martes,' ',miercoles,' ',jueves,' ',viernes,' ',salon,' ',cupo ) LIKE '%"+valor+"%'";
        
        model= new DefaultTableModel(null, titulos);
        
        conectar cc=new conectar();
        Connection cn=cc.conexion();
        
        try {
            Statement st=cn.createStatement();
            ResultSet result=st.executeQuery(sql);
            while(result.next())
            {
                registro[0]=result.getString("clvasig");
                registro[1]=result.getString("grupo");
                registro[2]=result.getString("mat");
                registro[3]=result.getString("profesor");
                registro[4]=result.getString("lunes");
                registro[5]=result.getString("martes");
                registro[6]=result.getString("miercoles");
                registro[7]=result.getString("jueves");
                registro[8]=result.getString("viernes");
                registro[9]=result.getString("salon");
                registro[10]=result.getString("cupo");
                model.addRow(registro);
            }
            table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void cargar(){
        String [] titulos={"clvasig","grupo","mat","profesor","lunes","martes","miercoles","jueves","viernes","salon","cupo"};
        String [] registro=new String[11];
        String sql="SELECT * FROM unsemestre";
        
        model= new DefaultTableModel(null, titulos);
        
        conectar cc=new conectar();
        Connection cn=cc.conexion();
        
        try {
            Statement st=cn.createStatement();
            ResultSet result=st.executeQuery(sql);
            while(result.next())
            {
                registro[0]=result.getString("clvasig");
                registro[1]=result.getString("grupo");
                registro[2]=result.getString("mat");
                registro[3]=result.getString("profesor");
                registro[4]=result.getString("lunes");
                registro[5]=result.getString("martes");
                registro[6]=result.getString("miercoles");
                registro[7]=result.getString("jueves");
                registro[8]=result.getString("viernes");
                registro[9]=result.getString("salon");
                registro[10]=result.getString("cupo");
                model.addRow(registro);
            }
            table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
    void borrare(){
        String a;
        a=buscar.getText();
        String sql= "DELETE FROM unsemestre WHERE clvasig='"+a+"'";
        conectar cc= new conectar();
        Connection cn= cc.conexion();
        
        try {
            PreparedStatement st=cn.prepareStatement(sql);
            st.execute();
             JOptionPane.showMessageDialog( null,"Registro Borrado");
             cargar();
             limpiar();
             bloquear();
 
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog( null,ex);
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        clave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botoncomenzar = new javax.swing.JButton();
        botonborrar = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Buscar: ");

        buscar.setText("jTextField1");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        jLabel2.setText("Clave: ");

        botoncomenzar.setText("Comenzar");
        botoncomenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncomenzarActionPerformed(evt);
            }
        });

        botonborrar.setText("Borrar");
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });

        botonsalir.setText("Salir");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscar)
                    .addComponent(clave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(botonborrar)
                .addGap(83, 83, 83)
                .addComponent(botoncomenzar)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoncomenzar)
                    .addComponent(botonborrar)
                    .addComponent(botonsalir))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botoncomenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncomenzarActionPerformed

        desbloquear();// TODO add your handling code here:
    }//GEN-LAST:event_botoncomenzarActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed

        borrare();// TODO add your handling code here:
    }//GEN-LAST:event_botonborrarActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
filtrar(buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoncomenzar;
    private javax.swing.JButton botonsalir;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}

